In [135]:
from astropy import units as u
from astropy.coordinates import SkyCoord
import numpy as np

#This is an example of the ra and dec data that the converstion will call to

c = SkyCoord(ra=10.625*u.degree, dec=41.2*u.degree, frame='icrs')

#This is cartesian conversion

def x (ra,dec):
    x = (np.cos(ra)*np.sin(dec))
    return x


def y (ra,dec):
    y = (np.cos(dec)*np.sin(ra))
    return y

#Example 

#x(c.ra,c.dec)
#y(c.ra,c.dec)

def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)

def pol2cart(rho, phi):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)

In [136]:
#Here we make a string manually to import the data, 
#For each lens there should be 11 numbers 
#First we have the uncertainty, then we have the dRA and dDec for the lensing galaxy
#Then we have the dRA and dDec for each image (4 images each)
#If we have 3 lenses, we should have 33 numbers in our chain, and so on...


a= """0.003 0.358 0.567 1.066 0.323 0.0 0.0 0.721 1.159 -0.157 1.021 0.008 1.152 0.636 2.42 0.792 1.458 -0.456 0.0 0.0 0.768 1.662"""

#Note that for right now I just include two lenses, we will include all 8 lenses and 
#all we have to do is change one variable ("numLenses" in the cell below

In [137]:
a= a.split(" ")
numLenses = 2
numImages = 4
oldData = np.zeros((numLenses,3,numImages))
newData = np.zeros((numLenses,3,numImages))

i=0
j=0
k=0
count=0;
while (i< numLenses):
    uncert= a[count]
    count=count+1;
    xChange=a[count]
    count=count+1
    yChange=a[count]
    count=count+1
    while (j< numImages):
        oldData[i][0][j] = float(a[count]) - float(xChange)
        count=count+1;
        oldData[i][1][j] = float(a[count]) - float(yChange)
        count=count+1;
        oldData[i][2][j]= float(uncert);
        j=j+1;
    i=i+1;
    j=0

    
i=0
j=0
k=0

while (i<numLenses):
    while (j<numImages):
        newData[i][0][j] = x(oldData[i][0][j], oldData[i][1][j])
        newData[i][1][j] = y(oldData[i][0][j], oldData[i][1][j])
        newData[i][2][j] = y(oldData[i][2][j], oldData[i][2][j])
        newData[i][0][j],newData[i][1][j] = cart2pol(newData[i][0][j], newData[i][1][j])
        #newData[i][0][j],newData[i][1][j] = pol2cart(newData[i][0][j], newData[i][1][j])
        j=j+1;
    i=i+1;
    j=0
print(newData)

[[[ 0.65719787  0.58345686  0.59912387  0.58447406]
  [ 1.85381203 -2.61037531  0.5141671  -0.85921828]
  [ 0.00299998  0.00299998  0.00299998  0.00299998]]

 [[ 0.94405297  0.85762441  0.77363047  0.81637191]
  [ 1.52170175  2.97904967 -1.88833424 -0.24012243]
  [ 0.00799966  0.00799966  0.00799966  0.00799966]]]
