In [20]:
from astropy import units as u
from astropy.coordinates import SkyCoord
import numpy as np

#This is an example of the ra and dec data that the converstion will call to

c = SkyCoord(ra=10.625*u.degree, dec=41.2*u.degree, frame='icrs')

#This is cartesian conversion

def x (ra,dec):
    x = (np.cos(ra)*np.sin(dec))
    return x


def y (ra,dec):
    y = (np.cos(dec)*np.sin(ra))
    return y

#Example 

#x(c.ra,c.dec)
#y(c.ra,c.dec)

def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)

def pol2cart(rho, phi):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)

In [21]:
#Here we make a string manually to import the data, 
#For each lens there should be 11 numbers 
#First we have the uncertainty, then we have the dRA and dDec for the lensing galaxy
#Then we have the dRA and dDec for each image (4 images each)
#If we have 3 lenses, we should have 33 numbers in our chain, and so on...



In [25]:
file1 = open('lensData.txt','r')
Lines = file1.read().replace('\n',' ');


a= Lines.split(" ")

numLenses = 8
numImages = 4
oldData = np.zeros((numLenses,3,numImages))
newData = np.zeros((numLenses,3,numImages))

i=0
j=0
k=0
count=0;
while (i< numLenses):
    uncert= a[count]
    count=count+1;
    xChange=a[count]
    count=count+1
    yChange=a[count]
    count=count+1
    while (j< numImages):
        oldData[i][0][j] = float(a[count]) - float(xChange)
        count=count+1;
        oldData[i][1][j] = float(a[count]) - float(yChange)
        count=count+1;
        oldData[i][2][j]= float(uncert);
        j=j+1;
    i=i+1;
    j=0

    
i=0
j=0
k=0

while (i<numLenses):
    while (j<numImages):
        newData[i][0][j] = x(oldData[i][0][j], oldData[i][1][j])
        newData[i][1][j] = y(oldData[i][0][j], oldData[i][1][j])
        newData[i][2][j] = y(oldData[i][2][j], oldData[i][2][j])
        newData[i][0][j],newData[i][1][j] = cart2pol(newData[i][0][j], newData[i][1][j])
        #newData[i][0][j],newData[i][1][j] = pol2cart(newData[i][0][j], newData[i][1][j])
        j=j+1;
    i=i+1;
    j=0
print(newData)

[[[ 6.57197867e-01  5.83456856e-01  5.99123870e-01  5.84474059e-01]
  [ 1.85381203e+00 -2.61037531e+00  5.14167102e-01 -8.59218282e-01]
  [ 2.99998200e-03  2.99998200e-03  2.99998200e-03  2.99998200e-03]]

 [[ 9.45193387e-01  8.57624412e-01  7.73630470e-01  8.16371906e-01]
  [ 1.52238976e+00  2.97904967e+00 -1.88833424e+00 -2.40122434e-01]
  [ 7.99965867e-03  7.99965867e-03  7.99965867e-03  7.99965867e-03]]

 [[ 6.63712573e-01  7.97050525e-01  6.45303820e-01  7.38457527e-01]
  [ 2.19523852e+00  1.65517633e+00  1.01585758e+00 -1.81826895e+00]
  [ 2.99998200e-03  2.99998200e-03  2.99998200e-03  2.99998200e-03]]

 [[ 7.96485468e-01  6.97263512e-01  8.87345699e-01  2.49295031e-01]
  [-2.45948882e-01 -8.71601069e-01 -1.61146573e+00  2.18815271e+00]
  [ 4.99991667e-03  4.99991667e-03  4.99991667e-03  4.99991667e-03]]

 [[ 7.33622379e-01  7.06204288e-01  6.32586855e-01  8.39519444e-01]
  [ 1.22756877e+00 -1.78236973e+00 -2.12438798e+00  3.04205705e+00]
  [ 2.99998200e-03  2.99998200e-03  2.99